version: 2
jobs: 
  build:
    docker:
      - image: amazonlinux

    working_directory: ~/repo

    steps:
      - checkout

      - run:
        name: Install Python 3.6
        command: |
          amazon-linux-extras install python3 -y

      - run:
        name: Install AWS CLI
        command: |
          pip3 install awscli

      - run:
        name: Install Hugo
        command: |
          cp hugo_installation_config.txt /etc/yum.repos.d/CentOS-hugo.repo
          yum install -y hugo
          hugo version
